### ISSUE TITLE
Nav Bar Home Button Style

### ISSUE THREAD

**Issue by zmikaya** [next2e/next2e.github.io#9]
It looks like their is some floating 2e text next to the nav bar home button in the left corner doesn't present well. Perhaps it wasn't even supposed to be there.

![nav_bar](https://cloud.githubusercontent.com/assets/8031669/17501937/785b4892-5db1-11e6-967a-38024c222332.png)

**Comment by cmnord** [comment]
yeah it looks super ugly... lemme fix rn

**Comment by cmnord** [comment]
285b46bc21f15d96f339c0642b6eb568beaea598
